### ISSUE TITLE
The  right way to process data

### ISSUE THREAD

**Issue by zjcerwin** [changzhisun/entrel-joint-mrt#1]
Thank you for the great work, I want to reproduce the result in your paper, I process the ACE dataset as follows:
1. Preprocess the original ACE05 dataset using Miwa`s script, after that, I got plenty of files endswith .split.ann
2. Run ace2005_data_preprocess.py to construct data.json, during that, I met assertion error in line 103: assert sent_id == sent_id_tmp
3. Modify line 103 to: if sent_id != sent_id_tmp:continue,  then  rerun the script, it goes without error.
I wonder if it`s ok to skip the assertion error?

**Comment by changzhisun** [comment]
Line 103 code is to ensure that two entities appear in the same sentence.
According to your modification, the relation cross sentence will be discard.
But I didn‘t have this problem. You could print this relation and check with original *.split.ann file.

**Comment by zjcerwin** [comment]
Maybe there`s something wrong with my step1.
Could you print the sentence numbers of train, dev, and test? It would be helpful to debug preprocess steps.
Thanks a lot.

**Comment by changzhisun** [comment]
> Maybe there`s something wrong with my step1.
> Could you print the sentence numbers of train, dev, and test? It would be helpful to debug preprocess steps.
> Thanks a lot.

Could you provide an email?

**Comment by ChijunZhang** [comment]
> > Maybe there`s something wrong with my step1.
> > Could you print the sentence numbers of train, dev, and test? It would be helpful to debug preprocess steps.
> > Thanks a lot.
> 
> Could you provide an email?

zhangjunchi@westlake.edu.cn
