### ISSUE TITLE
ACE2005

### ISSUE THREAD

**Issue by bobobe** [changzhisun/entrel-joint-mrt#2]
我想跑一下你们的模型，能提供一下ACE2005的数据吗，谢谢。mjkbyb@gmail.com

**Comment by yin-hong** [comment]
> 我想跑一下你们的模型，能提供一下ACE2005的数据吗，谢谢。[mjkbyb@gmail.com](mailto:mjkbyb@gmail.com)

请问你拿到了吗？不过ACE2005好像是付费的吧

**Comment by changzhisun** [comment]
If you have the license of ACE2005, I could share the preprocessed data for you.
